# Generated by Django 4.2.7 on 2023-11-22 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=100)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=200)),
                ("is_nice_habit", models.BooleanField()),
                ("frequency", models.PositiveIntegerField(default=1)),
                ("reward", models.CharField(blank=True, max_length=200, null=True)),
                ("time_required", models.PositiveIntegerField()),
                ("is_public", models.BooleanField(default=False)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
